config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'
  
  resources :contacts do
    resources :comments
    resources :phone_numbers
  end
  resources :jobs do
    resources :comments
    resources :type
  end
  
  resources :phone_types
  

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  job_type   :string
#

class Job < ActiveRecord::Base
  JOB_TYPES = ["PUR-Pick Up Rental", "SR-Service Rental", "RPR-Repair", "EMS-Event Management Services"]
  
  has_many :comments, as: :commentable, dependent: :destroy
  has_one :type, as: :typeable
  # belongs_to :true, polymorphic: true
end

app/controllers/jobs_controller.rb
# == Schema Information
#
# Table name: jobs
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  job_type   :string
#

class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @commentable = @job
    @comments = @commentable.comments
    @comment = Comment.new
    
    @typeable = @job
    @type = @typeable.type
    @type = Type.new
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @type = @job.build_type
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :job_type)
    end
end

app/helpers/jobs_helper.rb
# == Schema Information
#
# Table name: jobs
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  job_type   :string
#

module JobsHelper

  def job_type_options
    [["Pick Up Rental", "PUR"], ["Service Rental", "SR"], ["Repair", "RPR"], ["Event Management Services", "EMS"]]
  end

end

app/views/jobs/_form.html.erb
<%# simple_form_for(@job, html: { class: 'form-horizontal' }) do |f| %>
<%= simple_form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.select :job_type, job_type_options, {:include_blank => '-select-'}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<!--Jobs-->
<p id="notice"><%= notice %></p>

<%= page_header_index("Jobs <span class='badge'>#{@jobs.count}</span>") %>

<div class="row">
  <div class="col-sm-2">
    <%= link_to 'New Job', new_job_path, class: 'btn btn-primary btn-block' %>
  </div>
  <div class="col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-sm-4">
            <label>Search</label>
            <input class="form-control"></input>
          </div>
        </div>
      </div>
      <ul class="list-group">
        <% @jobs.each do |job| %>
          <li class="list-group-item">
            <div style="background-color: green; width:80px;color:white;padding: 0 4px;margin-right:4px;display:inline-block;text-align:right;">Status</div><%= link_to job.name, job %> <%= content_tag(:small, "#{job.comments.count} Comments", class: '') %>
            <%= link_to 'Edit', edit_job_path(job), class: 'pull-right' %>
          </li>
        <% end %>
      </ul>
      <%= content_tag(:div, class: "panel-footer") do %>
        <%= content_tag(:small, "Displaying #{@jobs.count} jobs") %>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @job.name %> <small><%= @job.job_type %></small></h1>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

<div class="row">
  <div class="col-sm-8">
  </div>
  <div class="col-sm-4">
    <h2>Comments</h2>
    
    <%= render "comments/comments" %>
    <%= render "comments/form" %>
  </div>
</div>